### ISSUE TITLE
Error when sending hex color string to color item

### ISSUE THREAD

**Issue by boc-tothefuture** [boc-tothefuture/openhab-jruby#341] opened 2021-10-29 20:52 UTC
In my production environment I get the following error message when doing the following command:

```
 led << '#FF0000'
```

in which led is a Color item. 

This is the offending line of code
```
  QuantityType.new(raw_hue.to_big_decimal, ::Units::DEGREE_ANGLE)
```

```
2021-10-29 16:39:59.368 [ERROR] [rulesupport.shared.simple.SimpleRule] - org.openhab.core.library.unit.Units is not a type/class (TypeError)
In rule: Turn on motion LED
/etc/openhab/automation/lib/ruby/gem_home/gems/openhab-scripting-4.8.0/lib/openhab/dsl/types/hsb_type.rb:153:in `hue'
/etc/openhab/automation/lib/ruby/gem_home/gems/openhab-scripting-4.8.0/lib/openhab/dsl/types/hsb_type.rb:178:in `to_s'
/etc/openhab/automation/lib/ruby/gem_home/gems/openhab-scripting-4.8.0/lib/openhab/dsl/items/generic_item.rb:59:in `command'
/etc/openhab/automation/lib/ruby/gem_home/gems/openhab-scripting-4.8.0/lib/openhab/dsl/items/ensure.rb:55:in `command'
/etc/openhab/automation/lib/ruby/gem_home/gems/openhab-scripting-4.8.0/lib/openhab/dsl/items/timed_command.rb:47:in `command'
/etc/openhab/automation/jsr223/ruby/personal/esp_home.rb:31:in `block in <main>'
```

We have a test for this specific thing which passes.. So I am confused why it is failing in production and also why it woudln't be able to find Units.

**Comment by ccutrer** [comment] 2021-10-29 20:54
It's ::Units getting overwritten by the extension after the script loads, but before your rule executes. We can work around by referring to it by OpenHAB::DSL::Units, but we really need to fix the extension at some point to quit overwriting everything.

**Comment by boc-tothefuture** [comment] 2021-10-30 02:09
The problem is if we override what the extension does (I assume you mean the Java side here) I don't think we will get it merged.  In order to get it merged it needs to work in the GUI without our library.  The expectation is that the elements that are available in one language is available in all languages.  Or at least, I would expect a lot of push back.

**Comment by ccutrer** [comment] 2021-10-30 02:33
I'm proposing only blocking the classes getting imported into the global namespace (like you're already doing with File), since they're not usable as such on the Ruby side. The global variables (like `$ir`) would still come through. And the Ruby-proxy-for-Java-classes are still available in the Ruby side with their full names.

**Comment by boc-tothefuture** [comment] 2021-10-30 14:46
What makes them not usable on the Ruby side? I know we don't need them for our library usage - but are they not usable at all if you didn't have our library? 

I removed File because it fundamentally broke JRuby. 

We would have to have a reason to remove them unrelated to our library or I don't think they will accept the PR.  The OpenHAB core team seems to want to be able to run things using GUI rules and wants parity across the languages in that context. 

I 100% agree that we don't need them if you are using our library.

**Comment by boc-tothefuture** [comment] 2021-10-30 14:52
Also, I wonder why it gets overwritten in my production environment but not when we test.

**Comment by ccutrer** [comment] 2021-10-30 14:52
Because they're not the Ruby proxy classes for the Java classes. They're the Java classes directly. Ie what you get when you do `org.openhab.core.types.UnDefType.java_class` from Ruby. So you can't call class methods on them, or create instances of them. This is why they're causing errors when they're accidentally getting referenced.

I'm not sure why you keep talking about the UI rules. They wouldn't be usable from a UI rule either. A UI rule would need to reference the classes fully to get the Ruby proxy class. It's not that our library is changing anything.

As for ability to get merged upstream, it seems they would accept it the same as the newer JavaScript plugin that has already been accepted which requires you to explicitly import everything you reference.

**Comment by ccutrer** [comment] 2021-10-30 14:55
> Also, I wonder why it gets overwritten in my production environment but not when we test. 
> 
> 

Afaict, there's no difference. I was able to reproduce with our testing framework as long as the test used an `after` or a rule triggered by something _not_ `on_start`. The top level constants are somehow getting set after the script loads, but before scriptLoaded is called.

**Comment by boc-tothefuture** [comment] 2021-10-30 15:03
I have never made a UI rule, so I don't know goes into them or how they work.  Let me open a separate issue to discuss this.

**Closed** 2021-10-30 15:19 UTC
Labels: bug
