### ISSUE TITLE
Quantity in case statement raised an exception

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#374] opened 2021-11-03 23:39 UTC
I encountered error when writing something like this:

```ruby
status = case Solar_AC_Power
         when '0 kW' then 'zero'
         when '1 kW'...'2 kW' then 'low production'
         when '2 kW'...'4 kW' then 'not bad'
         when '4 kW'...'7 kW' then 'decent'
         when '7 kW'...'10 kW' then 'good'
         when '10 kW'...'100 kW' then 'awesome!'
         else 'out of range'
         end
```

```
Number:Power     Solar_AC_Power  
```

The error:
```
09:36:55.838 [ERROR] [ript.internal.ScriptEngineManagerImpl] - Error during evaluation of script 'file:/openhab/conf/automation/jsr223/ruby/personal/test.rb': org.jruby.embed.EvalFailedException: java.lang.IllegalArgumentException: Invalid Quantity value: 1 kX
```

How did it become `1 kX` ?

**Comment by ccutrer** [comment] 2021-11-06 17:37
I'm fairly sure this a duplicate of #352

**Closed by ccutrer** 2021-11-06 17:37 UTC
