### ISSUE TITLE
HSBType.new is not available within a rule

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#435] opened 2021-11-30 00:35 UTC
This works:
```
require 'openhab'

color = HSBType.new(1,2,3)
```

But this doesn't:
```
require 'openhab'
rule 'test' do
  received_command Item1
  run do
    color = HSBType.new(1,2,3)
  end
end

Item1 << ON
```

The error:

```
10:34:31.686 [ERROR] [yobj.OpenHAB.DSL.Rules.AutomationRule] - undefined method `new' for #<Java::JavaLang::Class: org.openhab.core.library.types.HSBType> (NoMethodError)
```

**Comment by ccutrer** [comment] 2021-11-30 00:36
This is a duplicate of https://github.com/boc-tothefuture/openhab-jruby/issues/348

**Closed by ccutrer** 2021-11-30 00:36 UTC
